#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APTCONFIG="apt.conf.yaml"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" -p "${BASEDIR}/.dotbot-git/git.py" -p "${BASEDIR}/.dotbot-sudo/sudo.py" "${@}"

source /etc/os-release
case $ID in
    debian)
        echo "debian"
        sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${APTCONFIG}" -p "${BASEDIR}/.dotbot-apt/apt.py" "${@}"
        ;;
    *)
        echo "unknown distro ID: $ID, not doing anything special"
        ;;
esac
